// family/boot-inject.ts — Inject shared concept context into agent boot prompts.
// Phase 6 of Theorex: promotes hot concepts from shared graph into session prompts.

import type { Config } from "../cli/index.js";
import { resolve } from "node:path";
import { writeFileSync, mkdirSync } from "node:fs";
import { AxonStore } from "../axon/store.js";
import { resolvedSharedAxonPath } from "./paths.js";

export const DEFAULT_OUTPUT_PATH = resolve(
  process.env.THEOREX_SHARED_CONTEXT ??
    "/Users/eoh/.openclaw/workspace/theorex/SHARED_CONTEXT.md"
);

export interface BootInjectResult {
  outputPath: string;
  activeConcepts: number;
  totalConcepts: number;
  agentCount: number;
  duration_ms: number;
}

export async function generateBootContext(
  config: Config,
  outputPath: string = DEFAULT_OUTPUT_PATH,
  top: number | undefined,
  nowMs: number = Date.now(),
): Promise<BootInjectResult> {
  const sharedPath = resolvedSharedAxonPath(config.sharedAxonPath);
  const store = await AxonStore.load(sharedPath);
  if (config.coldStorePath) store.openCold(config.coldStorePath);

  const totalConcepts = store.graph.order;
  const sharedGraph = store.graph;
  const entries: Array<{
    conceptId: string;
    surface_form: string;
    score: number;
    agent: string;
    tier: string;
    updatedAt: string;
  }> = [];

  // Collect all ACTIVE tier concepts from shared graph
  for (const conceptId of sharedGraph.nodes()) {
    const attrs = sharedGraph.getNodeAttributes(conceptId) ?? {};
    const tier = attrs.relevance_tier ?? attrs.tier ?? "ACTIVE";
    if (tier === "ACTIVE" || tier === "MILD") {
      entries.push({
        conceptId,
        surface_form: attrs.surface_form ?? conceptId,
        score: attrs.importance_weight ?? attrs.frequency_count ?? 0,
        agent: attrs.agent_id ?? attrs.agent ?? "unknown",
        tier,
        updatedAt: attrs.last_seen ?? attrs.updatedAt,
      });
    }
  }

  entries.sort((a, b) => b.score - a.score);

  const activeByAgent = new Map<string, typeof entries>();
  for (const entry of entries) {
    if (!activeByAgent.has(entry.agent)) {
      activeByAgent.set(entry.agent, []);
    }
    activeByAgent.get(entry.agent)!.push(entry);
  }

  const PER_AGENT_CAP = top != null ? Math.ceil(top / Math.max(activeByAgent.size, 1)) : Infinity;

  const lines: string[] = [
    "# Theorex Shared Context — Fleet Brain",
    "",
    `Generated: ${new Date(nowMs).toISOString()}`,
    `Total concepts: ${totalConcepts} | Active: ${entries.length} | Agents: ${activeByAgent.size}`,
    `Top-N per agent: ${top ?? "all"}`,
    "",
    "## Active Concepts by Agent",
    "",
  ];

  for (const [agent, agentEntries] of activeByAgent.entries()) {
    const sorted = [...agentEntries].sort((a, b) => b.score - a.score);
    const capped = sorted.slice(0, PER_AGENT_CAP);
    lines.push(`## ${agent}`);
    for (const entry of capped) {
      const age = entry.updatedAt
        ? `${Math.round((nowMs - new Date(entry.updatedAt).getTime()) / 86400000)}d ago`
        : "unknown";
      lines.push(
        `- **${entry.surface_form}** \`${entry.conceptId}\` | score: ${entry.score.toFixed(3)} | ${age}`
      );
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(`_Generated by Theorex boot-inject at ${new Date(nowMs).toISOString()}_`);

  mkdirSync(resolve(outputPath, ".."), { recursive: true });
  writeFileSync(outputPath, lines.join("\n"), "utf-8");

  return {
    outputPath,
    activeConcepts: entries.length,
    totalConcepts,
    agentCount: activeByAgent.size,
    duration_ms: Date.now() - nowMs,
  };
}

export async function runBootInject(
  config: Config,
  outputPath?: string,
  top?: number,
): Promise<void> {
  const result = await generateBootContext(config, outputPath, top);
  console.log(
    `Boot context written: ${result.activeConcepts} active concepts → ${result.outputPath}`
  );
}
