// family/boot-inject.ts — Generate SHARED_CONTEXT.md from the shared axon.
// Phase 6: AI Family Shared Layer — Boot Injection
//
// Writes a compact markdown summary of ACTIVE-tier concepts from the shared web.
// This file is added once to openclaw.json memorySearch.extraPaths and agents
// load it automatically on every boot — no hook changes required.
//
// Output path: ~/.openclaw/workspace/theorex/SHARED_CONTEXT.md
// Token cost: ~150-400 tokens depending on how many ACTIVE concepts exist.

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { homedir } from "node:os";
import { AxonStore } from "../axon/store";
import { compositeScore, classifyTier } from "../axon/scorer";
import { resolvedSharedAxonPath } from "./paths";
import type { Config } from "../config";

const DEFAULT_OUTPUT_PATH = join(homedir(), ".openclaw", "workspace", "theorex", "SHARED_CONTEXT.md");

export interface BootInjectResult {
  readonly outputPath: string;
  readonly activeConcepts: number;
  readonly totalConcepts: number;
}

/**
 * Human-readable relative age from an ISO timestamp.
 * Returns: "today", "yesterday", "3 days ago", "2 weeks ago", "3 months ago".
 * This gives agents a sense of how fresh each concept is.
 */
function relativeAge(lastSeen: string, nowMs: number): string {
  const days = (nowMs - new Date(lastSeen).getTime()) / 86_400_000;
  if (days < 1)   return "today";
  if (days < 2)   return "yesterday";
  if (days < 14)  return Math.floor(days) + " days ago";
  if (days < 60)  return Math.floor(days / 7) + " weeks ago";
  return Math.floor(days / 30) + " months ago";
}

/**
 * Generate SHARED_CONTEXT.md from ACTIVE-tier nodes in the shared axon.
 * Groups concepts by agent_id. Sorts by composite score (hottest first).
 * Shows relative age and frequency so agents know what's fresh vs stale.
 */
export async function generateBootContext(
  config: Config,
  outputPath: string = DEFAULT_OUTPUT_PATH,
  nowMs: number = Date.now(),
): Promise<BootInjectResult> {
  const sharedPath = resolvedSharedAxonPath(config.sharedAxonPath);
  const store = await AxonStore.load(sharedPath);
  // Phase 9: wake SLEEPING nodes so they can score and appear in boot context
  if (config.coldStorePath) store.openCold(config.coldStorePath);

  const totalConcepts = store.graph.order;

  type Entry = { label: string; score: number; age: string; freq: number };
  const activeByAgent = new Map<string, Entry[]>();

  for (const key of store.graph.nodes()) {
    const attrs = store.graph.getNodeAttributes(key);
    const neighborStrengths = store.graph
      .neighbors(key)
      .map((nbr) => {
        const edgeKey = store.graph.edge(key, nbr);
        return edgeKey ? store.graph.getEdgeAttributes(edgeKey).strength : 0;
      });

    const score = compositeScore(attrs.last_seen, attrs.frequency_count, neighborStrengths, nowMs, config);
    const tier = classifyTier(score, config);

    // Include ACTIVE and MILD — LESS is too stale to be useful at boot
    if (tier === "LESS") continue;

    // Strip trailing punctuation artifacts from NLP extraction
    const label = attrs.surface_form.replace(/[:.!,;]+\s*$/, "").replace(/\s+/g, " ").trim();
    if (!label || label.length < 4) continue;
    if (label.endsWith("-")) continue;
    const BOOT_NOISE = new Set(["despite","however","therefore","still","it","this","that",
      "read","rate","check","floor","day","time","way","here","there","now","then"]);
    if (BOOT_NOISE.has(label.toLowerCase())) continue;

    const agent = attrs.agent_id || "unknown";
    if (!activeByAgent.has(agent)) activeByAgent.set(agent, []);
    activeByAgent.get(agent)!.push({
      label,
      score,
      age: relativeAge(attrs.last_seen, nowMs),
      freq: attrs.frequency_count,
    });
  }

  const activeConcepts = [...activeByAgent.values()].reduce((n, list) => n + list.length, 0);

  const lines: string[] = [
    "# Shared Agent Context",
    "> Generated by Theorex — " + new Date(nowMs).toISOString().slice(0, 10),
    "> " + activeConcepts + " active concepts across " + activeByAgent.size + " agent(s)",
    "",
  ];

  for (const [agent, entries] of activeByAgent.entries()) {
    lines.push("## " + agent);
    // Sort hottest first: highest composite score at top
    const sorted = [...entries].sort((a, b) => b.score - a.score);
    for (const entry of sorted) {
      // Show frequency when meaningfully high (>3 mentions signals importance)
      const tag = entry.freq > 3
        ? " _(" + entry.age + ", x" + entry.freq + ")_"
        : " _(" + entry.age + ")_";
      lines.push("- " + entry.label + tag);
    }
    lines.push("");
  }

  if (activeConcepts === 0) {
    lines.push("_No active shared concepts yet. Run: theorex promote --agent <id>_");
  }

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, lines.join("\n"), "utf-8");

  return { outputPath, activeConcepts, totalConcepts };
}
