import { test, expect, beforeEach, afterEach } from "bun:test";
import { mkdtemp, rm, mkdir } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { readFile } from "node:fs/promises";
import { generateBootContext } from "../../src/family/boot-inject";
import { writeToAgent } from "../../src/family/write";
import { promoteToShared } from "../../src/family/promote";
import { DEFAULT_CONFIG } from "../../src/config";

let tmpDir: string;

beforeEach(async () => {
  tmpDir = await mkdtemp(join(tmpdir(), "theorex-boot-test-"));
  await mkdir(join(tmpDir, "agents"), { recursive: true });
});

afterEach(async () => {
  await rm(tmpDir, { recursive: true, force: true });
});

const config = {
  ...DEFAULT_CONFIG,
  agentAxonDir: join("", ""),  // will override per test
  sharedAxonPath: "",
  promotionThreshold: 0,       // promote everything for test clarity
};

test("generateBootContext creates SHARED_CONTEXT.md", async () => {
  const sharedPath = join(tmpDir, "shared-axon.json");
  const outputPath = join(tmpDir, "SHARED_CONTEXT.md");
  const overrideConfig = { ...config, agentAxonDir: join(tmpDir, "agents"), sharedAxonPath: sharedPath };

  await writeToAgent("main", "trading risk signal profit equity", overrideConfig);
  await writeToAgent("main", "trading risk signal profit equity", overrideConfig);
  await promoteToShared("main", overrideConfig);

  const result = await generateBootContext(overrideConfig, outputPath);
  expect(result.outputPath).toBe(outputPath);
  expect(result.totalConcepts).toBeGreaterThanOrEqual(0);

  const content = await readFile(outputPath, "utf-8");
  expect(content).toContain("# Shared Agent Context");
  expect(content).toContain("Generated by Theorex");
});

test("generateBootContext groups concepts by agent", async () => {
  const sharedPath = join(tmpDir, "shared-axon.json");
  const outputPath = join(tmpDir, "SHARED_CONTEXT.md");
  const overrideConfig = { ...config, agentAxonDir: join(tmpDir, "agents"), sharedAxonPath: sharedPath };

  await writeToAgent("main", "trading risk signal profit equity drawdown", overrideConfig);
  await writeToAgent("main", "trading risk signal profit equity drawdown", overrideConfig);
  await promoteToShared("main", overrideConfig);
  await writeToAgent("qwen-sage", "machine learning inference embeddings neural", overrideConfig);
  await writeToAgent("qwen-sage", "machine learning inference embeddings neural", overrideConfig);
  await promoteToShared("qwen-sage", overrideConfig);

  await generateBootContext(overrideConfig, outputPath);
  const content = await readFile(outputPath, "utf-8");

  expect(content).toContain("## main");
  expect(content).toContain("## qwen-sage");
});

test("generateBootContext produces empty message when no shared concepts", async () => {
  const sharedPath = join(tmpDir, "shared-axon.json");
  const outputPath = join(tmpDir, "SHARED_CONTEXT.md");
  const overrideConfig = { ...config, agentAxonDir: join(tmpDir, "agents"), sharedAxonPath: sharedPath };

  const result = await generateBootContext(overrideConfig, outputPath);
  expect(result.activeConcepts).toBe(0);

  const content = await readFile(outputPath, "utf-8");
  expect(content).toContain("No active shared concepts");
});

test("generateBootContext excludes LESS-tier concepts", async () => {
  const sharedPath = join(tmpDir, "shared-axon.json");
  const outputPath = join(tmpDir, "SHARED_CONTEXT.md");
  // High thresholds so everything is LESS tier
  const overrideConfig = {
    ...config,
    agentAxonDir: join(tmpDir, "agents"),
    sharedAxonPath: sharedPath,
    activeThreshold: 0.99,
    mildThreshold: 0.98,
  };

  await writeToAgent("main", "trading risk", overrideConfig);
  await promoteToShared("main", { ...overrideConfig, promotionThreshold: 0 });
  const result = await generateBootContext(overrideConfig, outputPath);
  expect(result.activeConcepts).toBe(0);
});
